include:
  # Taken from https://docs.gitlab.com/ee/ci/yaml/workflow.html#workflowrules-templates
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
  - check
  - build
  - test

.build_regular_template:
  stage: build
  image: gcc:12
  before_script:
    - apt-get update && apt-get install -y cmake ninja-build xorriso
  script:
    - mkdir build
    - cd build
    - cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE && ninja

# Gitlab CI environment template that enables Nix on the command line,
# including nix-build and nix-shell.
.nix_build_template:
  interruptible: true
  tags:
    - native-nix-v2
  before_script:
    - git config --global --add url."${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/".insteadOf "git@${CI_SERVER_HOST}:"
    - git config --global --add url."${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/".insteadOf "ssh://git@${CI_SERVER_HOST}/"

check:format:
  extends:
    - .nix_build_template
  stage: check
  script:
    - nix-shell --run "./scripts/format.sh --check"

check:nix-shell:
  extends:
    - .nix_build_template
  stage: check
  script:
    - nix-shell --pure --run "echo nix-shell works"

build:regular_debug:
  extends:
    - .build_regular_template
  variables:
    CMAKE_BUILD_TYPE: "Debug"

build:regular_release:
  extends:
    - .build_regular_template
  variables:
    CMAKE_BUILD_TYPE: "Release"

# Tests the Nix build and that the promised attribute structure is valid.
build:nix:
  extends:
    - .nix_build_template
  stage: build
  script:
    - nix-build nix/release.nix -A verifyTestsAttributeStructure


# All test use the same base to boot. Hence, we test here that the hello-world
# test comes up.

test:vm:hello-world-boots:multiboot1:
  extends:
    - .nix_build_template
  stage: test
  variables:
    # For sotest-protocol-parser
    NIXPKGS_ALLOW_UNFREE: 1
  script:
    - nix-build nix/release.nix -A testRuns.qemu.kvm.multiboot.hello-world

test:vm:hello-world-boots:iso:
  extends:
    - .nix_build_template
  stage: test
  variables:
    NIXPKGS_ALLOW_UNFREE: 1
  script:
    - nix-build nix/release.nix -A testRuns.qemu.kvm.iso.hello-world

test:vm:hello-world-boots:efi:
  extends:
    - .nix_build_template
  stage: test
  variables:
    NIXPKGS_ALLOW_UNFREE: 1
  script:
    - nix-build nix/release.nix -A testRuns.qemu.kvm.efi.hello-world

test:vm:hello-world-boots:xen-pvh:
  extends:
    - .nix_build_template
  stage: test
  variables:
    NIXPKGS_ALLOW_UNFREE: 1
  script:
    - nix-build nix/release.nix -A testRuns.chv.kvm.xen-pvh.hello-world

# We run all guest tests but allow them to fail. They are made for real
# hardware and our own virtualization solutions, which aren't tested here.
test:vm:kvm:
  extends:
    - .nix_build_template
  stage: test
  # No real dependency but doesn't make sense to run without the basic tests.
  needs:
    - test:vm:hello-world-boots:multiboot1
    - test:vm:hello-world-boots:iso
    - test:vm:hello-world-boots:efi
    - test:vm:hello-world-boots:xen-pvh
  allow_failure: true
  parallel:
    matrix:
      - VMM:
          - chv
          - qemu
        # Generated by running:
        # nix-build nix/release.nix -A testNames && \
        #   cat result | xargs -I {} echo - {}
        GUEST_TEST:
          - cpuid
          - emulator
          - emulator-syscall
          - exceptions
          - fpu
          # Already tested above.
          # - hello-world
          - lapic-modes
          - lapic-priority
          - lapic-timer
          - msr
          - pagefaults
          - pit-timer
          - sgx
          - sgx-launch-control
          - tsc
          - vmx
  variables:
    NIXPKGS_ALLOW_UNFREE: 1
  script:
    - echo "Running ${GUEST_TEST} in ${VMM}/kvm"
    - nix-build nix/release.nix -A testRuns.${VMM}.kvm.default.${GUEST_TEST}

test:sotest:submit:
  extends:
    - .nix_build_template
  stage: test
  # No real dependency but doesn't make sense to run without the basic tests.
  needs:
    - test:vm:hello-world-boots:iso
    - test:vm:hello-world-boots:efi
  script:
    - nix-build nix/release.nix -A sotest
    - RUN_SOTEST=$(nix-build nix/cbspkgs.nix -A cyberus.cbspkgs.run-sotest --no-out-link)/bin/run_sotest
    - $RUN_SOTEST http://sotest:3000 result/project-config.yaml
      --boot_files "result/bundle.zip"
      --user "$CI_PROJECT_NAMESPACE - $GITLAB_USER_LOGIN"
      --url "$CI_PROJECT_URL/commit/$CI_COMMIT_SHA"
      --name "$CI_PROJECT_NAME $CI_COMMIT_REF_SLUG"
      --priority 0
      --testrun_id_file sotest_testrun_id.txt
      --nopoll
  artifacts:
    expire_in: 1 week
    paths:
      - sotest_testrun_id.txt

test:sotest:poll:
  extends:
    - .nix_build_template
  stage: test
  needs:
    - test:sotest:submit
  timeout: 12h
  script:
    - POLL_SOTEST=$(nix-build nix/cbspkgs.nix -A cyberus.cbspkgs.run-sotest --no-out-link)/bin/poll_sotest
    - $POLL_SOTEST http://sotest:3000
      --id "$(cat sotest_testrun_id.txt)"
      --junit-xml sotest-report.xml
      --extract-records-to https://elastic.vpn.cyberus-technology.de
  artifacts:
    paths:
      - sotest-report.xml
    reports:
      junit: sotest-report.xml
    when: always
