# This is a separate file to keep the dozens of jobs separated from the actual
# real CI jobs. The test runs here are mostly informational.

name: Optional

on:
  merge_group:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Transitively builds the CMake project in Nix and executes the specified
  # local VMM test runs.
  nix_optional_local_test_runs:
    strategy:
      fail-fast: false
      matrix:
        vmm:
          - chv
          - qemu
        test:
          - cpuid
          - emulator
          - emulator-syscall
          - exceptions
          - fpu
          # Already tested above.
          # - hello-world
          - lapic-modes
          - lapic-priority
          - lapic-timer
          - msr
          - pagefaults
          - pit-timer
          - sgx
          - sgx-launch-control
          - timing
          - tsc
          - vmx
    name: "Run ${{ matrix.test }}/${{ matrix.vmm }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-build nix/release.nix -A testRuns.${{ matrix.vmm }}.kvm.default.${{ matrix.test }}
